uploads = []
outputs = []

[[generated]]
id = "0ZzuUVMDYZDRESM_CMPuj"
uri = "file://artifacts/finance-mobile/assets/images/icon.png"
type = "image"
title = "finance app icon"

[[generated]]
id = "cn8q7nV0OXP6xLoZfVTQh"
uri = "file://artifacts/finance-mobile/assets/logo.png"
type = "image"
title = "guardia shield logo"

[[generated]]
id = "KgVyM4TPfUkuxLrU6i3u_"
uri = "file://artifacts/finance-mobile/assets/icon.png"
type = "image"
title = "guardia flat icon dark navy shield"

[[generated]]
id = "6dKAhpgWnbRZMk-jN0Et2"
uri = "file://artifacts/finance-mobile/assets/adaptive-icon.png"
type = "image"
title = "guardia adaptive icon white bg shield"
